services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: agrofreight_sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    restart: always
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
volumes:
  mssql_data:
