[project]
name = "agrofreight"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=2.3.3",
    "pyodbc>=5.3.0",
    "sqlalchemy>=2.0.44",
]

[tool.basedpyright]
typeCheckingMode = "standard"
